//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditProfiles.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EditProfiles.Properties.MyResources", typeof(MyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Strings_ButtonFindReplace {
            get {
                return ResourceManager.GetString("Strings_ButtonFindReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Strings_ButtonStopTest {
            get {
                return ResourceManager.GetString("Strings_ButtonStopTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}{0}{2}{0}{3}{0}{1}{0}.
        /// </summary>
        internal static string Strings_CurrentFileName {
            get {
                return ResourceManager.GetString("Strings_CurrentFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Profile Test\ShortFiles.
        /// </summary>
        internal static string Strings_Debug_InitialDirectory {
            get {
                return ResourceManager.GetString("Strings_Debug_InitialDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ip17|ip18.
        /// </summary>
        internal static string Strings_Debug_TextBoxFind {
            get {
                return ResourceManager.GetString("Strings_Debug_TextBoxFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ip22|ip23.
        /// </summary>
        internal static string Strings_Debug_TextBoxReplace {
            get {
                return ResourceManager.GetString("Strings_Debug_TextBoxReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not specified.
        /// </summary>
        internal static string Strings_DefaultTextBoxValues {
            get {
                return ResourceManager.GetString("Strings_DefaultTextBoxValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to errors.log.
        /// </summary>
        internal static string Strings_Error_FileName {
            get {
                return ResourceManager.GetString("Strings_Error_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose at least a file..
        /// </summary>
        internal static string Strings_Error_FileNamesEmpty {
            get {
                return ResourceManager.GetString("Strings_Error_FileNamesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find what cannot be empty..
        /// </summary>
        internal static string Strings_Error_FindWhatBlank {
            get {
                return ResourceManager.GetString("Strings_Error_FindWhatBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred. Please check &quot;errors.log&quot; file..
        /// </summary>
        internal static string Strings_ErrorLogFile {
            get {
                return ResourceManager.GetString("Strings_ErrorLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change protection..
        /// </summary>
        internal static string Strings_ErrorProtectionCaption {
            get {
                return ResourceManager.GetString("Strings_ErrorProtectionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{2}{0} Provided password failed to change protection level {0} File Name:  {1}{0}{2}{0}.
        /// </summary>
        internal static string Strings_ErrorProtectionLevel {
            get {
                return ResourceManager.GetString("Strings_ErrorProtectionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your password..
        /// </summary>
        internal static string Strings_ErrorProtectionMessage {
            get {
                return ResourceManager.GetString("Strings_ErrorProtectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}Current Time: {0}{2}File name: {3}{2}{1}{2}.
        /// </summary>
        internal static string Strings_ErrorTraceErrors {
            get {
                return ResourceManager.GetString("Strings_ErrorTraceErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to occ.
        /// </summary>
        internal static string Strings_FileDialogDefault {
            get {
                return ResourceManager.GetString("Strings_FileDialogDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCC files (*.occ)|*.occ|All files (*.*)|*.*.
        /// </summary>
        internal static string Strings_FileDialogFilter {
            get {
                return ResourceManager.GetString("Strings_FileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: {0} of {1}.
        /// </summary>
        internal static string Strings_FileProcessBar {
            get {
                return ResourceManager.GetString("Strings_FileProcessBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditProfiles.
        /// </summary>
        internal static string Strings_FolderName {
            get {
                return ResourceManager.GetString("Strings_FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test completed. Total errors: {0}.
        /// </summary>
        internal static string Strings_FormEndTest {
            get {
                return ResourceManager.GetString("Strings_FormEndTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No test module loaded..
        /// </summary>
        internal static string Strings_FormStartModuleTest {
            get {
                return ResourceManager.GetString("Strings_FormStartModuleTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select file(s)..
        /// </summary>
        internal static string Strings_FormStartTest {
            get {
                return ResourceManager.GetString("Strings_FormStartTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profiles v{0}.
        /// </summary>
        internal static string Strings_FormTitle {
            get {
                return ResourceManager.GetString("Strings_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}) ({2}) Finalized..
        /// </summary>
        internal static string Strings_GarbageCollection {
            get {
                return ResourceManager.GetString("Strings_GarbageCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find what: Use | to separate items.
        /// </summary>
        internal static string Strings_LabelFind {
            get {
                return ResourceManager.GetString("Strings_LabelFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password to edit file(s).
        /// </summary>
        internal static string Strings_LabelPassword {
            get {
                return ResourceManager.GetString("Strings_LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with: Use | to separate items.
        /// </summary>
        internal static string Strings_LabelReplace {
            get {
                return ResourceManager.GetString("Strings_LabelReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Files.
        /// </summary>
        internal static string Strings_ModifedFolderName {
            get {
                return ResourceManager.GetString("Strings_ModifedFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module: {0} of {1}.
        /// </summary>
        internal static string Strings_ModuleProcessBar {
            get {
                return ResourceManager.GetString("Strings_ModuleProcessBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO change required:{1}{0}{1}.
        /// </summary>
        internal static string Strings_NoChanges {
            get {
                return ResourceManager.GetString("Strings_NoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select file(s) to modify. Press and hold CTRL key to select multiple files..
        /// </summary>
        internal static string Strings_OpenFileDialog {
            get {
                return ResourceManager.GetString("Strings_OpenFileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change required: {2} Find a match:  {0}{2} Replaced with: {1}{2}.
        /// </summary>
        internal static string Strings_ParamsChanged {
            get {
                return ResourceManager.GetString("Strings_ParamsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}{7}{1} End time: {0}{1}Total test time: {2:d2} day(s), {3:d2} hour(s), {4:d2} min(s), {5:d2} sec(s), {6:d3} millisecond(s){1}{7}.
        /// </summary>
        internal static string Strings_TestEnd {
            get {
                return ResourceManager.GetString("Strings_TestEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test start time: {0}.
        /// </summary>
        internal static string Strings_TestStart {
            get {
                return ResourceManager.GetString("Strings_TestStart", resourceCulture);
            }
        }
    }
}
